<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Dish;
use App\Functions\Helpers;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dishes = [
        
            [   
                "name" => "Pollo alla Kung Pao",    
                "cover_img" => "dish/pollokungpao.jpeg",    
                "ingredients" => "pollo, peperoncini, arachidi",
                "description" => "Un classico piatto cinese fatto con pollo saltato in padella, peperoncini e arachidi.",
                "price" => "10.99",
                "show" => true,         
                "restaurant_id" => [2],
            ],
            [   
                "name" => "Pollo alla Kung Pao",    
                "cover_img" => "dish/pollokungpao.jpeg",    
                "ingredients" => "pollo, peperoncini, arachidi",
                "description" => "Un classico piatto cinese fatto con pollo saltato in padella, peperoncini e arachidi.",
                "price" => "10.99",
                "show" => true,         
                "restaurant_id" => [3],
            ],
            [   
                "name" => "Pollo alla Kung Pao",    
                "cover_img" => "dish/pollokungpao.jpeg",    
                "ingredients" => "pollo, peperoncini, arachidi",
                "description" => "Un classico piatto cinese fatto con pollo saltato in padella, peperoncini e arachidi.",
                "price" => "10.99",
                "show" => true,         
                "restaurant_id" => [18],
            ],
            [   
                "name" => "Pollo alla Kung Pao",    
                "cover_img" => "dish/pollokungpao.jpeg",    
                "ingredients" => "pollo, peperoncini, arachidi",
                "description" => "Un classico piatto cinese fatto con pollo saltato in padella, peperoncini e arachidi.",
                "price" => "10.99",
                "show" => true,         
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Ravioli al vapore",
                "cover_img" => "dish/raviolialvapore.jpeg",    
                "ingredients" => "carne di maiale, zenzero, cipolla verde",
                "description" => "Deliziosi ravioli ripieni di carne di maiale, zenzero e cipolla verde.",
                "price" => "8.50",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Ravioli al vapore",
                "cover_img" => "dish/raviolialvapore.jpeg",    
                "ingredients" => "carne di maiale, zenzero, cipolla verde",
                "description" => "Deliziosi ravioli ripieni di carne di maiale, zenzero e cipolla verde.",
                "price" => "8.50",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Ravioli al vapore",
                "cover_img" => "dish/raviolialvapore.jpeg",    
                "ingredients" => "carne di maiale, zenzero, cipolla verde",
                "description" => "Deliziosi ravioli ripieni di carne di maiale, zenzero e cipolla verde.",
                "price" => "8.50",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Zuppa di wonton",
                "cover_img" => "https://images.unsplash.com/photo-1559948271-7d5c98d2e951?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                "ingredients" => "wonton, brodo di pollo, spinaci",
                "description" => "Una zuppa di wonton tradizionale con wonton ripieni di carne di maiale, servita in brodo di pollo con spinaci.",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Zuppa di wonton",
                "cover_img" => "https://images.unsplash.com/photo-1559948271-7d5c98d2e951?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                "ingredients" => "wonton, brodo di pollo, spinaci",
                "description" => "Una zuppa di wonton tradizionale con wonton ripieni di carne di maiale, servita in brodo di pollo con spinaci.",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Maiale agrodolce",
                "cover_img" => "dish/maialeagrodolce.jpg",    
                "ingredients" => "maiale, ananas, peperoni",
                "description" => "Un piatto di maiale agrodolce fatto con cubetti di maiale, ananas e peperoni in una salsa dolce e acidula.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Maiale agrodolce",
                "cover_img" => "dish/maialeagrodolce.jpg",    
                "ingredients" => "maiale, ananas, peperoni",
                "description" => "Un piatto di maiale agrodolce fatto con cubetti di maiale, ananas e peperoni in una salsa dolce e acidula.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Maiale agrodolce",
                "cover_img" => "dish/maialeagrodolce.jpg",    
                "ingredients" => "maiale, ananas, peperoni",
                "description" => "Un piatto di maiale agrodolce fatto con cubetti di maiale, ananas e peperoni in una salsa dolce e acidula.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
        
            [
                "name" => "Chow mein di verdure",
                "cover_img" => "https://images.unsplash.com/photo-1609690963718-0b55905aef78?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=999&q=80",
                "ingredients" => "tagliatelle, verdure miste, salsa di soia",
                "description" => "Un piatto di chow mein vegetariano fatto con tagliatelle saltate in padella e verdure miste in una salsa di soia.",
                "price" => "9.50",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Chow mein di verdure",
                "cover_img" => "https://images.unsplash.com/photo-1609690963718-0b55905aef78?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=999&q=80",
                "ingredients" => "tagliatelle, verdure miste, salsa di soia",
                "description" => "Un piatto di chow mein vegetariano fatto con tagliatelle saltate in padella e verdure miste in una salsa di soia.",
                "price" => "9.50",
                "show" => true,
                "restaurant_id" => [18],
            ],
        
            [
                "name" => "Gamberi in salsa di aglio",
                "cover_img" => "dish/gamberiallaglio.jpg",    
                "ingredients" => "gamberi, aglio, peperoncino",
                "description" => "Gamberi saltati in padella con aglio e peperoncino in una salsa piccante.",
                "price" => "13.52",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Gamberi in salsa di aglio",
                "cover_img" => "dish/gamberiallaglio.jpg",    
                "ingredients" => "gamberi, aglio, peperoncino",
                "description" => "Gamberi saltati in padella con aglio e peperoncino in una salsa piccante.",
                "price" => "13.52",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Gamberi in salsa di aglio",
                "cover_img" => "dish/gamberiallaglio.jpg",    
                "ingredients" => "gamberi, aglio, peperoncino",
                "description" => "Gamberi saltati in padella con aglio e peperoncino in una salsa piccante.",
                "price" => "13.52",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Gamberi in salsa di aglio",
                "cover_img" => "dish/gamberiallaglio.jpg",    
                "ingredients" => "gamberi, aglio, peperoncino",
                "description" => "Gamberi saltati in padella con aglio e peperoncino in una salsa piccante.",
                "price" => "13.52",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Anatra alla pechinese",
                "cover_img" => "dish/anatraallapechinese.jpg",
                "ingredients" => "anatra, cipolla, pancake",
                "description" => "Un piatto di anatra alla pechinese fatto con anatra cotta in umido, cipolla e pancake sottili.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Anatra alla pechinese",
                "cover_img" => "dish/anatraallapechinese.jpg",
                "ingredients" => "anatra, cipolla, pancake",
                "description" => "Un piatto di anatra alla pechinese fatto con anatra cotta in umido, cipolla e pancake sottili.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Anatra alla pechinese",
                "cover_img" => "dish/anatraallapechinese.jpg",
                "ingredients" => "anatra, cipolla, pancake",
                "description" => "Un piatto di anatra alla pechinese fatto con anatra cotta in umido, cipolla e pancake sottili.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Anatra alla pechinese",
                "cover_img" => "dish/anatraallapechinese.jpg",
                "ingredients" => "anatra, cipolla, pancake",
                "description" => "Un piatto di anatra alla pechinese fatto con anatra cotta in umido, cipolla e pancake sottili.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
                    
        
            [
                "name" => "Manzo alla Szechuan",    
                "cover_img" => "dish/manzoallaszechuan.jpg",    
                "ingredients" => "manzo, peperoncini secchi, tofu",
                "description" => "Un piatto piccante della cucina Szechuan, fatto con bocconcini di manzo, peperoncini secchi e tofu.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
        
            [
                "name" => "Gamberi in salsa di fagioli neri",
                "cover_img" => "dish/gamberisalsafagiolineri.jpg",    
                "ingredients" => "gamberi, salsa di fagioli neri, zenzero, aglio",
                "description" => "Un piatto salato e saporito con gamberi freschi e salsa di fagioli neri, insaporiti con zenzero e aglio.",
                "price" => "14.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
        
            [
                "name" => "Sushi assortito",    
                "cover_img" => "https://images.unsplash.com/photo-1625938145312-c18f06f53be0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",    
                "ingredients" => "riso, pesce crudo, alga nori, wasabi, salsa di soia",
                "description" => "Un assortimento di sushi fresco, fatto con riso giapponese, pesce crudo, alga nori e condimenti come wasabi e salsa di soia.",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Sushi assortito",    
                "cover_img" => "https://images.unsplash.com/photo-1625938145312-c18f06f53be0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",    
                "ingredients" => "riso, pesce crudo, alga nori, wasabi, salsa di soia",
                "description" => "Un assortimento di sushi fresco, fatto con riso giapponese, pesce crudo, alga nori e condimenti come wasabi e salsa di soia.",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Sushi assortito",    
                "cover_img" => "https://images.unsplash.com/photo-1625938145312-c18f06f53be0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",    
                "ingredients" => "riso, pesce crudo, alga nori, wasabi, salsa di soia",
                "description" => "Un assortimento di sushi fresco, fatto con riso giapponese, pesce crudo, alga nori e condimenti come wasabi e salsa di soia.",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Tonkatsu",
                "cover_img" => "dish/tonkatsu.jpg",
                "ingredients" => "maiale, panko, uovo, farina, cavolo",
                "description" => "Un piatto di maiale fritto impanato con panko, servito con cavolo tagliato sottile.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Tonkatsu",
                "cover_img" => "dish/tonkatsu.jpg",
                "ingredients" => "maiale, panko, uovo, farina, cavolo",
                "description" => "Un piatto di maiale fritto impanato con panko, servito con cavolo tagliato sottile.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Tonkatsu",
                "cover_img" => "dish/tonkatsu.jpg",
                "ingredients" => "maiale, panko, uovo, farina, cavolo",
                "description" => "Un piatto di maiale fritto impanato con panko, servito con cavolo tagliato sottile.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Tonkatsu",
                "cover_img" => "dish/tonkatsu.jpg",
                "ingredients" => "maiale, panko, uovo, farina, cavolo",
                "description" => "Un piatto di maiale fritto impanato con panko, servito con cavolo tagliato sottile.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Soba noodles",
                "cover_img" => "dish/sobanoodles.jpg",
                "ingredients" => "soba noodles, dashi, mirin, sake, nori",
                "description" => "Un piatto di soba noodles in brodo dashi con mirin, sake e alga nori.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Soba noodles",
                "cover_img" => "dish/sobanoodles.jpg",
                "ingredients" => "soba noodles, dashi, mirin, sake, nori",
                "description" => "Un piatto di soba noodles in brodo dashi con mirin, sake e alga nori.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
            
            [
                "name" => "Okonomiyaki",
                "cover_img" => "https://images.unsplash.com/photo-1629579436553-6b34e5ddd9de?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
                "ingredients" => "farina, uovo, cavolo, bacon, salsa okonomiyaki",
                "description" => "Un pancake salato fatto con farina, uova, cavolo, bacon e salsa okonomiyaki.",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Okonomiyaki",
                "cover_img" => "https://images.unsplash.com/photo-1629579436553-6b34e5ddd9de?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
                "ingredients" => "farina, uovo, cavolo, bacon, salsa okonomiyaki",
                "description" => "Un pancake salato fatto con farina, uova, cavolo, bacon e salsa okonomiyaki.",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Okonomiyaki",
                "cover_img" => "https://images.unsplash.com/photo-1629579436553-6b34e5ddd9de?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
                "ingredients" => "farina, uovo, cavolo, bacon, salsa okonomiyaki",
                "description" => "Un pancake salato fatto con farina, uova, cavolo, bacon e salsa okonomiyaki.",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
            
            [
                "name" => "Tempura",
                "cover_img" => "https://images.unsplash.com/photo-1636381310731-0e851c654cff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
                "ingredients" => "gamberi, verdure miste, farina, uovo, acqua frizzante",
                "description" => "Un piatto di gamberi e verdure miste fritte in pastella di farina, uovo e acqua frizzante.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Tempura",
                "cover_img" => "https://images.unsplash.com/photo-1636381310731-0e851c654cff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
                "ingredients" => "gamberi, verdure miste, farina, uovo, acqua frizzante",
                "description" => "Un piatto di gamberi e verdure miste fritte in pastella di farina, uovo e acqua frizzante.",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
        
            
            [
                "name" => "Yakitori",
                "cover_img" => "https://cdn.chefincamicia.com/images/a41c789988215311a8b922614a675764.1920.jpg",
                "ingredients" => "pollo, salsa teriyaki, cipollotto",
                "description" => "Spiedini di pollo glassati con salsa teriyaki e cipollotto.",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Yakitori",
                "cover_img" => "https://cdn.chefincamicia.com/images/a41c789988215311a8b922614a675764.1920.jpg",
                "ingredients" => "pollo, salsa teriyaki, cipollotto",
                "description" => "Spiedini di pollo glassati con salsa teriyaki e cipollotto.",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Yakitori",
                "cover_img" => "https://cdn.chefincamicia.com/images/a41c789988215311a8b922614a675764.1920.jpg",
                "ingredients" => "pollo, salsa teriyaki, cipollotto",
                "description" => "Spiedini di pollo glassati con salsa teriyaki e cipollotto.",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
            
            [
                "name" => "Gyudon",
                "cover_img" => "https://thewoksoflife.com/wp-content/uploads/2016/02/gyudon-9.jpg",
                "ingredients" => "manzo, cipolla, soia, mirin, uovo",
                "description" => "Un piatto di riso con carne di manzo tagliata sottile, cipolla, salsa di soia e mirin, servito con uovo crudo sulla parte superiore.",
                "price" => "14.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
        
            [
                "name" => "Sushi",
                "cover_img" => "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80",
                "ingredients" => "Riso, Pesce crudo",
                "description" => "Il sushi è un piatto giapponese composto da riso insaporito con aceto di riso, zucchero e sale, accompagnato da pesce crudo o verdure.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Sushi",
                "cover_img" => "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80",
                "ingredients" => "Riso, Pesce crudo",
                "description" => "Il sushi è un piatto giapponese composto da riso insaporito con aceto di riso, zucchero e sale, accompagnato da pesce crudo o verdure.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [3],
            ],
            [
                "name" => "Sushi",
                "cover_img" => "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80",
                "ingredients" => "Riso, Pesce crudo",
                "description" => "Il sushi è un piatto giapponese composto da riso insaporito con aceto di riso, zucchero e sale, accompagnato da pesce crudo o verdure.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
            [
                "name" => "Sushi",
                "cover_img" => "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80",
                "ingredients" => "Riso, Pesce crudo",
                "description" => "Il sushi è un piatto giapponese composto da riso insaporito con aceto di riso, zucchero e sale, accompagnato da pesce crudo o verdure.",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [20],
            ],
        
            [
                "name" => "Ramen",
                "cover_img" => "https://images.unsplash.com/photo-1617421753170-46511a8d73fc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1965&q=80",
                "ingredients" => "Brodo di carne, Noodles, Carne di maiale, Uova, Verdure",
                "description" => "Il ramen è una zuppa giapponese a base di noodles in brodo di carne, accompagnata da carne di maiale, uova e verdure.",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [18],
            ],
        
            [
                "name" => "Margherita",
                "cover_img" => "dish/margherita.png",
                "ingredients" => "pomodoro, mozzarella, basilico",
                "description" => "Pizza con pomodoro, mozzarella e basilico fresco",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [4],            
            ],
            [
                "name" => "Margherita",
                "cover_img" => "dish/margherita.png",
                "ingredients" => "pomodoro, mozzarella, basilico",
                "description" => "Pizza con pomodoro, mozzarella e basilico fresco",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [6],            
            ],
            [
                "name" => "Margherita",
                "cover_img" => "dish/margherita.png",
                "ingredients" => "pomodoro, mozzarella, basilico",
                "description" => "Pizza con pomodoro, mozzarella e basilico fresco",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [1],            
            ],
            [
                "name" => "Margherita",
                "cover_img" => "dish/margherita.png",
                "ingredients" => "pomodoro, mozzarella, basilico",
                "description" => "Pizza con pomodoro, mozzarella e basilico fresco",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [14],            
            ],
            [
                "name" => "Margherita",
                "cover_img" => "dish/margherita.png",
                "ingredients" => "pomodoro, mozzarella, basilico",
                "description" => "Pizza con pomodoro, mozzarella e basilico fresco",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [17],            
            ],
        
            [
                "name" => "Prosciutto e funghi",
                "cover_img" => "dish/prosciuttoefunghi.png",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Prosciutto e funghi",
                "cover_img" => "dish/prosciuttoefunghi.png",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Prosciutto e funghi",
                "cover_img" => "dish/prosciuttoefunghi.png",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Prosciutto e funghi",
                "cover_img" => "dish/prosciuttoefunghi.png",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
            [
                "name" => "Prosciutto e funghi",
                "cover_img" => "dish/prosciuttoefunghi.png",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Diavola",
                "cover_img" => "dish/diavola.jpg",
                "ingredients" => "pomodoro, mozzarella, salame piccante, peperoncino",
                "description" => "Pizza con pomodoro, mozzarella, salame piccante e peperoncino",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Diavola",
                "cover_img" => "dish/diavola.jpg",
                "ingredients" => "pomodoro, mozzarella, salame piccante, peperoncino",
                "description" => "Pizza con pomodoro, mozzarella, salame piccante e peperoncino",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Diavola",
                "cover_img" => "dish/diavola.jpg",
                "ingredients" => "pomodoro, mozzarella, salame piccante, peperoncino",
                "description" => "Pizza con pomodoro, mozzarella, salame piccante e peperoncino",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
        
            [
                "name" => "Quattro formaggi",
                "cover_img" => "https://www.insidetherustickitchen.com/wp-content/uploads/2020/07/Quattro-formaggi-pizza-square-Inside-the-rustic-kitchen.jpg",
                "ingredients" => "gorgonzola, mozzarella, parmigiano reggiano, pecorino romano",
                "description" => "Pizza con quattro formaggi: gorgonzola, mozzarella, parmigiano reggiano e pecorino romano",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
            [
                "name" => "Quattro formaggi",
                "cover_img" => "https://www.insidetherustickitchen.com/wp-content/uploads/2020/07/Quattro-formaggi-pizza-square-Inside-the-rustic-kitchen.jpg",
                "ingredients" => "gorgonzola, mozzarella, parmigiano reggiano, pecorino romano",
                "description" => "Pizza con quattro formaggi: gorgonzola, mozzarella, parmigiano reggiano e pecorino romano",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Calzone",
                "cover_img" => "https://www.allrecipes.com/thmb/Bwkz2gVOQUJcPYSzOJgD94XDi5Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/18874-Real-Italian-Calzones-ddmfs-127-4x3-1-a30a0e72801f42bcb0643ed4b57e8a3c.jpg",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi",
                "description" => "Calzone ripieno di pomodoro, mozzarella, prosciutto cotto e funghi champignon",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
        
            [
                "name" => "Capricciosa",
                "cover_img" => "https://upload.wikimedia.org/wikipedia/commons/2/2a/Pizza_capricciosa.jpg",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi, carciofini, olive nere",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto, funghi champignon, carciofini e olive nere",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Capricciosa",
                "cover_img" => "https://upload.wikimedia.org/wikipedia/commons/2/2a/Pizza_capricciosa.jpg",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi, carciofini, olive nere",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto, funghi champignon, carciofini e olive nere",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Capricciosa",
                "cover_img" => "https://upload.wikimedia.org/wikipedia/commons/2/2a/Pizza_capricciosa.jpg",
                "ingredients" => "pomodoro, mozzarella, prosciutto cotto, funghi, carciofini, olive nere",
                "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto, funghi champignon, carciofini e olive nere",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Vegetariana",
                "cover_img" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
                "ingredients" => "pomodoro, mozzarella, melanzane, zucchine, peperoni, funghi",
                "description" => "Pizza vegetariana con pomodoro, mozzarella, melanzane, zucchine, peperoni e funghi",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Vegetariana",
                "cover_img" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
                "ingredients" => "pomodoro, mozzarella, melanzane, zucchine, peperoni, funghi",
                "description" => "Pizza vegetariana con pomodoro, mozzarella, melanzane, zucchine, peperoni e funghi",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Vegetariana",
                "cover_img" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
                "ingredients" => "pomodoro, mozzarella, melanzane, zucchine, peperoni, funghi",
                "description" => "Pizza vegetariana con pomodoro, mozzarella, melanzane, zucchine, peperoni e funghi",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Vegetariana",
                "cover_img" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
                "ingredients" => "pomodoro, mozzarella, melanzane, zucchine, peperoni, funghi",
                "description" => "Pizza vegetariana con pomodoro, mozzarella, melanzane, zucchine, peperoni e funghi",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
            [
                "name" => "Vegetariana",
                "cover_img" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
                "ingredients" => "pomodoro, mozzarella, melanzane, zucchine, peperoni, funghi",
                "description" => "Pizza vegetariana con pomodoro, mozzarella, melanzane, zucchine, peperoni e funghi",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Tonno e cipolla",
                "cover_img" => "https://www.bofrost.it/on/demandware.static/-/Sites-IT-master-catalog/default/dwe1d74287/images/15196-Pizza-Tonno-e-Cipolla-R.jpg",
                "ingredients" => "pomodoro, mozzarella, tonno, cipolla rossa",
                "description" => "Pizza con pomodoro, mozzarella, tonno e cipolla rossa",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Tonno e cipolla",
                "cover_img" => "https://www.bofrost.it/on/demandware.static/-/Sites-IT-master-catalog/default/dwe1d74287/images/15196-Pizza-Tonno-e-Cipolla-R.jpg",
                "ingredients" => "pomodoro, mozzarella, tonno, cipolla rossa",
                "description" => "Pizza con pomodoro, mozzarella, tonno e cipolla rossa",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Tonno e cipolla",
                "cover_img" => "https://www.bofrost.it/on/demandware.static/-/Sites-IT-master-catalog/default/dwe1d74287/images/15196-Pizza-Tonno-e-Cipolla-R.jpg",
                "ingredients" => "pomodoro, mozzarella, tonno, cipolla rossa",
                "description" => "Pizza con pomodoro, mozzarella, tonno e cipolla rossa",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
        
            [
                "name" => "Pizza bianca",
                "cover_img" => "dish/bianca.jpg",
                "ingredients" => "mozzarella, ricotta, prosciutto crudo, rucola",
                "description" => "Pizza bianca con mozzarella, ricotta, prosciutto crudo e rucola fresca",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [6],
            ],
            [
                "name" => "Pizza bianca",
                "cover_img" => "dish/bianca.jpg",
                "ingredients" => "mozzarella, ricotta, prosciutto crudo, rucola",
                "description" => "Pizza bianca con mozzarella, ricotta, prosciutto crudo e rucola fresca",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Pizza bianca",
                "cover_img" => "dish/bianca.jpg",
                "ingredients" => "mozzarella, ricotta, prosciutto crudo, rucola",
                "description" => "Pizza bianca con mozzarella, ricotta, prosciutto crudo e rucola fresca",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
            [
                "name" => "Pizza bianca",
                "cover_img" => "dish/bianca.jpg",
                "ingredients" => "mozzarella, ricotta, prosciutto crudo, rucola",
                "description" => "Pizza bianca con mozzarella, ricotta, prosciutto crudo e rucola fresca",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Hamburger",
                "cover_img" => "dish/hamburger.jpg",
                "ingredients" => "pane per hamburger, carne di manzo, lattuga, pomodoro, cipolla, formaggio cheddar",
                "description" => "Hamburger di carne di manzo con formaggio cheddar fuso, lattuga, pomodoro e cipolla su un morbido pane per hamburger",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Hamburger",
                "cover_img" => "dish/hamburger.jpg",
                "ingredients" => "pane per hamburger, carne di manzo, lattuga, pomodoro, cipolla, formaggio cheddar",
                "description" => "Hamburger di carne di manzo con formaggio cheddar fuso, lattuga, pomodoro e cipolla su un morbido pane per hamburger",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Hamburger",
                "cover_img" => "dish/hamburger.jpg",
                "ingredients" => "pane per hamburger, carne di manzo, lattuga, pomodoro, cipolla, formaggio cheddar",
                "description" => "Hamburger di carne di manzo con formaggio cheddar fuso, lattuga, pomodoro e cipolla su un morbido pane per hamburger",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Hamburger",
                "cover_img" => "dish/hamburger.jpg",
                "ingredients" => "pane per hamburger, carne di manzo, lattuga, pomodoro, cipolla, formaggio cheddar",
                "description" => "Hamburger di carne di manzo con formaggio cheddar fuso, lattuga, pomodoro e cipolla su un morbido pane per hamburger",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Hamburger",
                "cover_img" => "dish/hamburger.jpg",
                "ingredients" => "pane per hamburger, carne di manzo, lattuga, pomodoro, cipolla, formaggio cheddar",
                "description" => "Hamburger di carne di manzo con formaggio cheddar fuso, lattuga, pomodoro e cipolla su un morbido pane per hamburger",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Hot dog",
                "cover_img" => "dish/hotdog.png",
                "ingredients" => "pane per hot dog, salsiccia di pollo, ketchup, senape, cipolla fritta",
                "description" => "Hot dog con salsiccia di pollo, ketchup, senape e cipolla fritta, servito su un morbido pane per hot dog",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Hot dog",
                "cover_img" => "dish/hotdog.png",
                "ingredients" => "pane per hot dog, salsiccia di pollo, ketchup, senape, cipolla fritta",
                "description" => "Hot dog con salsiccia di pollo, ketchup, senape e cipolla fritta, servito su un morbido pane per hot dog",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Hot dog",
                "cover_img" => "dish/hotdog.png",
                "ingredients" => "pane per hot dog, salsiccia di pollo, ketchup, senape, cipolla fritta",
                "description" => "Hot dog con salsiccia di pollo, ketchup, senape e cipolla fritta, servito su un morbido pane per hot dog",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Hot dog",
                "cover_img" => "dish/hotdog.png",
                "ingredients" => "pane per hot dog, salsiccia di pollo, ketchup, senape, cipolla fritta",
                "description" => "Hot dog con salsiccia di pollo, ketchup, senape e cipolla fritta, servito su un morbido pane per hot dog",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Hot dog",
                "cover_img" => "dish/hotdog.png",
                "ingredients" => "pane per hot dog, salsiccia di pollo, ketchup, senape, cipolla fritta",
                "description" => "Hot dog con salsiccia di pollo, ketchup, senape e cipolla fritta, servito su un morbido pane per hot dog",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "BBQ ribs",
                "cover_img" => "https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
                "ingredients" => "costine di maiale, salsa barbecue, patate fritte",
                "description" => "Costine di maiale glassate con salsa barbecue, servite con patatine fritte",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "BBQ ribs",
                "cover_img" => "https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
                "ingredients" => "costine di maiale, salsa barbecue, patate fritte",
                "description" => "Costine di maiale glassate con salsa barbecue, servite con patatine fritte",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "BBQ ribs",
                "cover_img" => "https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
                "ingredients" => "costine di maiale, salsa barbecue, patate fritte",
                "description" => "Costine di maiale glassate con salsa barbecue, servite con patatine fritte",
                "price" => "16.99",
                "show" => true,
                "restaurant_id" => [19],
            ],          
        
            [
                "name" => "Mac and cheese",
                "cover_img" => "https://images.unsplash.com/photo-1487532195053-ae7d32261c6a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1138&q=80",
                "ingredients" => "pasta corta, formaggio cheddar, burro, latte",
                "description" => "Pasta corta con salsa di formaggio cheddar, burro e latte",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Mac and cheese",
                "cover_img" => "https://images.unsplash.com/photo-1487532195053-ae7d32261c6a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1138&q=80",
                "ingredients" => "pasta corta, formaggio cheddar, burro, latte",
                "description" => "Pasta corta con salsa di formaggio cheddar, burro e latte",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Mac and cheese",
                "cover_img" => "https://images.unsplash.com/photo-1487532195053-ae7d32261c6a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1138&q=80",
                "ingredients" => "pasta corta, formaggio cheddar, burro, latte",
                "description" => "Pasta corta con salsa di formaggio cheddar, burro e latte",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Mac and cheese",
                "cover_img" => "https://images.unsplash.com/photo-1487532195053-ae7d32261c6a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1138&q=80",
                "ingredients" => "pasta corta, formaggio cheddar, burro, latte",
                "description" => "Pasta corta con salsa di formaggio cheddar, burro e latte",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Fried chicken",
                "cover_img" => "dish/friedchiken.png",
                "ingredients" => "pollo fritto, salsa piccante, patatine fritte",
                "description" => "Pollo fritto croccante con salsa piccante, servito con patatine fritte",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Fried chicken",
                "cover_img" => "dish/friedchiken.png",
                "ingredients" => "pollo fritto, salsa piccante, patatine fritte",
                "description" => "Pollo fritto croccante con salsa piccante, servito con patatine fritte",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Fried chicken",
                "cover_img" => "dish/friedchiken.png",
                "ingredients" => "pollo fritto, salsa piccante, patatine fritte",
                "description" => "Pollo fritto croccante con salsa piccante, servito con patatine fritte",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Fried chicken",
                "cover_img" => "dish/friedchiken.png",
                "ingredients" => "pollo fritto, salsa piccante, patatine fritte",
                "description" => "Pollo fritto croccante con salsa piccante, servito con patatine fritte",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Fried chicken",
                "cover_img" => "dish/friedchiken.png",
                "ingredients" => "pollo fritto, salsa piccante, patatine fritte",
                "description" => "Pollo fritto croccante con salsa piccante, servito con patatine fritte",
                "price" => "12.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Clam chowder",
                "cover_img" => "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80",
                "ingredients" => "vongole, patate, pancetta, cipolla, brodo di pesce, panna",
                "description" => "Zuppa di vongole con patate, pancetta, cipolla, brodo di pesce e panna",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Clam chowder",
                "cover_img" => "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80",
                "ingredients" => "vongole, patate, pancetta, cipolla, brodo di pesce, panna",
                "description" => "Zuppa di vongole con patate, pancetta, cipolla, brodo di pesce e panna",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Clam chowder",
                "cover_img" => "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80",
                "ingredients" => "vongole, patate, pancetta, cipolla, brodo di pesce, panna",
                "description" => "Zuppa di vongole con patate, pancetta, cipolla, brodo di pesce e panna",
                "price" => "10.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Chili con carne",
                "cover_img" => "https://wips.plug.it/cips/buonissimo.org/cms/2013/03/chili-carne.jpg",
                "ingredients" => "carne macinata, fagioli rossi, pomodori pelati, cipolla, peperoncino",
                "description" => "Chili con carne fatto con carne macinata, fagioli rossi, pomodori pelati, cipolla e peperoncino",
                "price" => "9.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Buffalo wings",
                "cover_img" => "https://assets.bonappetit.com/photos/57ad22671b334044149753ed/1:1/w_2560%2Cc_limit/BAS-BEST-HOT-WINGS.jpg",
                "ingredients" => "ali di pollo, salsa piccante, burro",
                "description" => "Ali di pollo croccanti con salsa piccante al burro",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Buffalo wings",
                "cover_img" => "https://assets.bonappetit.com/photos/57ad22671b334044149753ed/1:1/w_2560%2Cc_limit/BAS-BEST-HOT-WINGS.jpg",
                "ingredients" => "ali di pollo, salsa piccante, burro",
                "description" => "Ali di pollo croccanti con salsa piccante al burro",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Philly cheesesteak",
                "cover_img" => "https://www.willcookforsmiles.com/wp-content/uploads/2022/09/Philly-Cheesesteak-closeup-sq.jpg",
                "ingredients" => "bistecca di manzo, cipolla, peperoni, formaggio provolone",
                "description" => "Sandwich con bistecca di manzo, cipolla, peperoni e formaggio provolone",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Philly cheesesteak",
                "cover_img" => "https://www.willcookforsmiles.com/wp-content/uploads/2022/09/Philly-Cheesesteak-closeup-sq.jpg",
                "ingredients" => "bistecca di manzo, cipolla, peperoni, formaggio provolone",
                "description" => "Sandwich con bistecca di manzo, cipolla, peperoni e formaggio provolone",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Philly cheesesteak",
                "cover_img" => "https://www.willcookforsmiles.com/wp-content/uploads/2022/09/Philly-Cheesesteak-closeup-sq.jpg",
                "ingredients" => "bistecca di manzo, cipolla, peperoni, formaggio provolone",
                "description" => "Sandwich con bistecca di manzo, cipolla, peperoni e formaggio provolone",
                "price" => "11.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Cornbread",
                "cover_img" => "dish/cornbread.jpg",
                "ingredients" => "farina di mais, zucchero, burro, latte",
                "description" => "Pane di farina di mais dolce e morbido, perfetto come accompagnamento ai piatti americani",
                "price" => "4.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Cornbread",
                "cover_img" => "dish/cornbread.jpg",
                "ingredients" => "farina di mais, zucchero, burro, latte",
                "description" => "Pane di farina di mais dolce e morbido, perfetto come accompagnamento ai piatti americani",
                "price" => "4.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Cornbread",
                "cover_img" => "dish/cornbread.jpg",
                "ingredients" => "farina di mais, zucchero, burro, latte",
                "description" => "Pane di farina di mais dolce e morbido, perfetto come accompagnamento ai piatti americani",
                "price" => "4.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Cornbread",
                "cover_img" => "dish/cornbread.jpg",
                "ingredients" => "farina di mais, zucchero, burro, latte",
                "description" => "Pane di farina di mais dolce e morbido, perfetto come accompagnamento ai piatti americani",
                "price" => "4.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Cornbread",
                "cover_img" => "dish/cornbread.jpg",
                "ingredients" => "farina di mais, zucchero, burro, latte",
                "description" => "Pane di farina di mais dolce e morbido, perfetto come accompagnamento ai piatti americani",
                "price" => "4.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Kebab Classico",
                "cover_img" => "https://images.dissapore.com/wp-content/uploads/2015/02/panino-al-kebab.jpg",
                "ingredients" => "pane, carne di pollo, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab classico con carne di pollo, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab Classico",
                "cover_img" => "https://images.dissapore.com/wp-content/uploads/2015/02/panino-al-kebab.jpg",
                "ingredients" => "pane, carne di pollo, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab classico con carne di pollo, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Kebab Classico",
                "cover_img" => "https://images.dissapore.com/wp-content/uploads/2015/02/panino-al-kebab.jpg",
                "ingredients" => "pane, carne di pollo, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab classico con carne di pollo, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
            [
                "name" => "Kebab Classico",
                "cover_img" => "https://images.dissapore.com/wp-content/uploads/2015/02/panino-al-kebab.jpg",
                "ingredients" => "pane, carne di pollo, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab classico con carne di pollo, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab Piccante",
                "cover_img" => "https://thumbs.dreamstime.com/b/insegna-di-panorama-con-il-kebab-turco-piccante-del-doner-92951000.jpg",
                "ingredients" => "pane, carne di manzo, insalata, pomodoro, peperoncino, salsa piccante",
                "description" => "Il kebab con carne di manzo piccante, insalata, pomodoro, peperoncino e salsa piccante",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab Piccante",
                "cover_img" => "https://thumbs.dreamstime.com/b/insegna-di-panorama-con-il-kebab-turco-piccante-del-doner-92951000.jpg",
                "ingredients" => "pane, carne di manzo, insalata, pomodoro, peperoncino, salsa piccante",
                "description" => "Il kebab con carne di manzo piccante, insalata, pomodoro, peperoncino e salsa piccante",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Kebab Piccante",
                "cover_img" => "https://thumbs.dreamstime.com/b/insegna-di-panorama-con-il-kebab-turco-piccante-del-doner-92951000.jpg",
                "ingredients" => "pane, carne di manzo, insalata, pomodoro, peperoncino, salsa piccante",
                "description" => "Il kebab con carne di manzo piccante, insalata, pomodoro, peperoncino e salsa piccante",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
            [
                "name" => "Kebab Piccante",
                "cover_img" => "https://thumbs.dreamstime.com/b/insegna-di-panorama-con-il-kebab-turco-piccante-del-doner-92951000.jpg",
                "ingredients" => "pane, carne di manzo, insalata, pomodoro, peperoncino, salsa piccante",
                "description" => "Il kebab con carne di manzo piccante, insalata, pomodoro, peperoncino e salsa piccante",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab Vegetariano",
                "cover_img" => "https://www.giallozafferano.it/images/195-19577/Kebab-vegetariano_780x520_wm.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tzatziki",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tzatziki",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab Vegetariano",
                "cover_img" => "https://www.giallozafferano.it/images/195-19577/Kebab-vegetariano_780x520_wm.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tzatziki",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tzatziki",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Kebab Vegetariano",
                "cover_img" => "https://www.giallozafferano.it/images/195-19577/Kebab-vegetariano_780x520_wm.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tzatziki",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tzatziki",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
            [
                "name" => "Kebab Vegetariano",
                "cover_img" => "https://www.giallozafferano.it/images/195-19577/Kebab-vegetariano_780x520_wm.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tzatziki",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tzatziki",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab Salmone",
                "cover_img" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2013/04/ricetta-panino-salmone-timo/jcr:content/imagePreview.img10.jpg/1414518403012.jpg",
                "ingredients" => "pane, salmone, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab con salmone affumicato, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab Salmone",
                "cover_img" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2013/04/ricetta-panino-salmone-timo/jcr:content/imagePreview.img10.jpg/1414518403012.jpg",
                "ingredients" => "pane, salmone, insalata, pomodoro, cipolla, salsa yogurt",
                "description" => "Il kebab con salmone affumicato, insalata, pomodoro, cipolla e salsa yogurt",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
        
            [
                "name" => "Kebab Gourmet",
                "cover_img" => "https://res.cloudinary.com/glovoapp/h_225,f_auto,q_auto/Stores/vjhmetmhony8lyslcgu8",
                "ingredients" => "pane, carne di manzo Wagyu, rucola, pomodoro secco, cipolla caramellata, salsa al tartufo",
                "description" => "Il kebab gourmet con carne di manzo Wagyu, rucola, pomodoro secco, cipolla caramellata e salsa al tartufo",
                "price" => "14.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
            [
                "name" => "Kebab Gourmet",
                "cover_img" => "https://res.cloudinary.com/glovoapp/h_225,f_auto,q_auto/Stores/vjhmetmhony8lyslcgu8",
                "ingredients" => "pane, carne di manzo Wagyu, rucola, pomodoro secco, cipolla caramellata, salsa al tartufo",
                "description" => "Il kebab gourmet con carne di manzo Wagyu, rucola, pomodoro secco, cipolla caramellata e salsa al tartufo",
                "price" => "14.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab con Patatine",
                "cover_img" => "https://media-cdn.tripadvisor.com/media/photo-s/0b/bd/fb/84/panino-con-kebab-provola.jpg",
                "ingredients" => "pane, carne di pollo, patatine fritte, insalata, pomodoro, cipolla, salsa kebab",
                "description" => "Il kebab con carne di pollo, patatine fritte, insalata, pomodoro, cipolla e salsa kebab",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab con Patatine",
                "cover_img" => "https://media-cdn.tripadvisor.com/media/photo-s/0b/bd/fb/84/panino-con-kebab-provola.jpg",
                "ingredients" => "pane, carne di pollo, patatine fritte, insalata, pomodoro, cipolla, salsa kebab",
                "description" => "Il kebab con carne di pollo, patatine fritte, insalata, pomodoro, cipolla e salsa kebab",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
            [
                "name" => "Kebab con Patatine",
                "cover_img" => "https://media-cdn.tripadvisor.com/media/photo-s/0b/bd/fb/84/panino-con-kebab-provola.jpg",
                "ingredients" => "pane, carne di pollo, patatine fritte, insalata, pomodoro, cipolla, salsa kebab",
                "description" => "Il kebab con carne di pollo, patatine fritte, insalata, pomodoro, cipolla e salsa kebab",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [19],
            ],
            [
                "name" => "Kebab con Patatine",
                "cover_img" => "https://media-cdn.tripadvisor.com/media/photo-s/0b/bd/fb/84/panino-con-kebab-provola.jpg",
                "ingredients" => "pane, carne di pollo, patatine fritte, insalata, pomodoro, cipolla, salsa kebab",
                "description" => "Il kebab con carne di pollo, patatine fritte, insalata, pomodoro, cipolla e salsa kebab",
                "price" => "8.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab Falafel",
                "cover_img" => "https://milleeunanottelivakebab.it/wp-content/uploads/2022/11/kebab-2-1024x692.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tahina",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tahina",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Kebab Falafel",
                "cover_img" => "https://milleeunanottelivakebab.it/wp-content/uploads/2022/11/kebab-2-1024x692.jpg",
                "ingredients" => "pane, falafel, insalata, pomodoro, cipolla, salsa tahina",
                "description" => "Il kebab vegetariano con falafel, insalata, pomodoro, cipolla e salsa tahina",
                "price" => "6.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
        
            [
                "name" => "Kebab Pollo Tikka",
                "cover_img" => "https://tadan-static.s3-eu-west-1.amazonaws.com/static/img/og-images/restaurants/terme-kebab-pisa.jpg",
                "ingredients" => "pane, pollo tikka, insalata, pomodoro, cipolla, salsa raita",
                "description" => "Il kebab con pollo tikka, insalata, pomodoro, cipolla e salsa raita",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
        
            [
                "name" => "Kebab Tandoori",
                "cover_img" => "https://res.cloudinary.com/glovoapp/h_225,f_auto,q_auto/Stores/z9tyvjkudvtt1ffxtohs",
                "ingredients" => "pane, pollo tandoori, insalata, pomodoro, cipolla, salsa al coriandolo",
                "description" => "Il kebab con pollo tandoori, insalata, pomodoro, cipolla e salsa al coriandolo",
                "price" => "7.99",
                "show" => true,
                "restaurant_id" => [13],
            ],
        
            [
                "name" => "Bistecca alla fiorentina",
                "cover_img" => "https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2016/02/BISTECCA-093022.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe",
                "description" => "La celebre bistecca alla fiorentina, con carne di manzo selezionata, cotta alla brace e servita al sangue",
                "price" => "22.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Bistecca alla fiorentina",
                "cover_img" => "https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2016/02/BISTECCA-093022.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe",
                "description" => "La celebre bistecca alla fiorentina, con carne di manzo selezionata, cotta alla brace e servita al sangue",
                "price" => "22.99",
                "show" => true,
                "restaurant_id" => [11],
            ],
            [
                "name" => "Bistecca alla fiorentina",
                "cover_img" => "https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2016/02/BISTECCA-093022.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe",
                "description" => "La celebre bistecca alla fiorentina, con carne di manzo selezionata, cotta alla brace e servita al sangue",
                "price" => "22.99",
                "show" => true,
                "restaurant_id" => [16],
            ],
            [
                "name" => "Bistecca alla fiorentina",
                "cover_img" => "https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2016/02/BISTECCA-093022.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe",
                "description" => "La celebre bistecca alla fiorentina, con carne di manzo selezionata, cotta alla brace e servita al sangue",
                "price" => "22.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Bistecca al pepe verde",
                "cover_img" => "dish/filettopepeverde.png",
                "ingredients" => "bistecca di manzo, sale, pepe verde, panna",
                "description" => "Bistecca di manzo con una gustosa salsa al pepe verde, a base di panna e aromi",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [8],
            ],
        
            [
                "name" => "Bistecca ai funghi",
                "cover_img" => "dish/filettofunghi.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, funghi misti, prezzemolo",
                "description" => "Bistecca di manzo servita con funghi misti trifolati e aromatizzati con prezzemolo",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca ai funghi",
                "cover_img" => "dish/filettofunghi.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, funghi misti, prezzemolo",
                "description" => "Bistecca di manzo servita con funghi misti trifolati e aromatizzati con prezzemolo",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [10],
            ],
            [
                "name" => "Bistecca ai funghi",
                "cover_img" => "dish/filettofunghi.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, funghi misti, prezzemolo",
                "description" => "Bistecca di manzo servita con funghi misti trifolati e aromatizzati con prezzemolo",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [11],
            ],
            [
                "name" => "Bistecca ai funghi",
                "cover_img" => "dish/filettofunghi.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, funghi misti, prezzemolo",
                "description" => "Bistecca di manzo servita con funghi misti trifolati e aromatizzati con prezzemolo",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Bistecca al gorgonzola",
                "cover_img" => "dish/bisteccagorgonzola.png",
                "ingredients" => "bistecca di manzo, sale, pepe, gorgonzola, panna",
                "description" => "Bistecca di manzo con una golosa salsa al gorgonzola, a base di panna e formaggio",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca al gorgonzola",
                "cover_img" => "dish/bisteccagorgonzola.png",
                "ingredients" => "bistecca di manzo, sale, pepe, gorgonzola, panna",
                "description" => "Bistecca di manzo con una golosa salsa al gorgonzola, a base di panna e formaggio",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
        
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [8],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [10],
            ],
            [
                "name" => "Bistecca alla griglia",
                "cover_img" => "dish/bisteccagriglia.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, erbe aromatiche",
                "description" => "La classica bistecca alla griglia, cotta al punto giusto e insaporita con erbe aromatiche",
                "price" => "18.99",
                "show" => true,
                "restaurant_id" => [11],
            ],
        
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [8],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [10],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [11],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
            [
                "name" => "Bistecca con patate al forno",
                "cover_img" => "dish/bisteccaconpatate.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, patate, rosmarino",
                "description" => "Bistecca di manzo accompagnata da patate al forno profumate con rosmarino",
                "price" => "20.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
        
        
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [8],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [10],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [12],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [15],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [16],
            ],
            [
                "name" => "Bistecca ai ferri",
                "cover_img" => "dish/bisteccaferri.jpg",
                "ingredients" => "bistecca di manzo, sale, pepe, aglio, prezzemolo",
                "description" => "Bistecca di manzo marinata con aglio e prezzemolo, poi cotta ai ferri",
                "price" => "19.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [1],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [2],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [4],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [5],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [7],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [8],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [9],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [10],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [11],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [12],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [14],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [15],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [16],
            ],
            [
                "name" => "Bistecca di maiale alla griglia",
                "cover_img" => "dish/bisteccamaiale.jpg",
                "ingredients" => "bistecca di maiale, sale, pepe, aglio",
                "description" => "Bistecca di maiale cotta alla griglia con aglio e pepe",
                "price" => "15.99",
                "show" => true,
                "restaurant_id" => [17],
            ],
        
        
            [
                "name" => "Bistecca di pollo al limone",
                "cover_img" => "dish/bisteccalimone.jpg",
                "ingredients" => "bistecca di pollo, sale, pepe, limone",
                "description" => "Bistecca di pollo marinata con limone e poi grigliata",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [1],             
            ],
            [
                "name" => "Bistecca di pollo al limone",
                "cover_img" => "dish/bisteccalimone.jpg",
                "ingredients" => "bistecca di pollo, sale, pepe, limone",
                "description" => "Bistecca di pollo marinata con limone e poi grigliata",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [2],             
            ],
            [
                "name" => "Bistecca di pollo al limone",
                "cover_img" => "dish/bisteccalimone.jpg",
                "ingredients" => "bistecca di pollo, sale, pepe, limone",
                "description" => "Bistecca di pollo marinata con limone e poi grigliata",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [16],             
            ],
            [
                "name" => "Bistecca di pollo al limone",
                "cover_img" => "dish/bisteccalimone.jpg",
                "ingredients" => "bistecca di pollo, sale, pepe, limone",
                "description" => "Bistecca di pollo marinata con limone e poi grigliata",
                "price" => "13.99",
                "show" => true,
                "restaurant_id" => [17],             
            ],
        
            [
                "name" => "Bistecca alla pizzaiola",
                "cover_img" => "dish/bisteccapizzaiola.jpg",
                "ingredients" => "bistecca di manzo, pomodoro, cipolla, origano, aglio",
                "description" => "Bistecca di manzo cotta in una gustosa salsa di pomodoro, cipolla e spezie",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [1],                  
            ],
            [
                "name" => "Bistecca alla pizzaiola",
                "cover_img" => "dish/bisteccapizzaiola.jpg",
                "ingredients" => "bistecca di manzo, pomodoro, cipolla, origano, aglio",
                "description" => "Bistecca di manzo cotta in una gustosa salsa di pomodoro, cipolla e spezie",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [7],                  
            ],
            [
                "name" => "Bistecca alla pizzaiola",
                "cover_img" => "dish/bisteccapizzaiola.jpg",
                "ingredients" => "bistecca di manzo, pomodoro, cipolla, origano, aglio",
                "description" => "Bistecca di manzo cotta in una gustosa salsa di pomodoro, cipolla e spezie",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [8],                  
            ],
            [
                "name" => "Bistecca alla pizzaiola",
                "cover_img" => "dish/bisteccapizzaiola.jpg",
                "ingredients" => "bistecca di manzo, pomodoro, cipolla, origano, aglio",
                "description" => "Bistecca di manzo cotta in una gustosa salsa di pomodoro, cipolla e spezie",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [12],                  
            ],
            [
                "name" => "Bistecca alla pizzaiola",
                "cover_img" => "dish/bisteccapizzaiola.jpg",
                "ingredients" => "bistecca di manzo, pomodoro, cipolla, origano, aglio",
                "description" => "Bistecca di manzo cotta in una gustosa salsa di pomodoro, cipolla e spezie",
                "price" => "21.99",
                "show" => true,
                "restaurant_id" => [14],                  
            ],
    ];

        foreach ($dishes as $dish) {
            foreach ($dish['restaurant_id'] as $dishfororder) {
                $newdish = new Dish();
                $newdish->name = $dish['name'];
                $newdish->slug = Helpers::generateSlug($newdish->name);
                $newdish->cover_img = $dish['cover_img'];
                $newdish->ingredients = $dish['ingredients'];
                $newdish->description = $dish['description'];
                $newdish->price = $dish['price'];
                $newdish->restaurant_id = $dishfororder;

                $newdish->save();
            }

            // POTREBBE SERVIRE DECOMMENTARLO.
            // $restaurants = $dish['restaurant_id'];
            // $newdish->restaurants()->sync($dish['restaurant_id']);
        }
    }
};